CREATE TABLE Teams (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  LeadUserId INTEGER,
  CreatedAt TEXT NOT NULL
);

CREATE TABLE Users (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Email TEXT NOT NULL UNIQUE,
  PasswordHash TEXT NOT NULL,
  Role TEXT NOT NULL DEFAULT 'user',
  CreatedAt TEXT NOT NULL,
  TeamId INTEGER
);

CREATE TABLE Leads (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  Phone TEXT NOT NULL DEFAULT '',
  Email TEXT NOT NULL DEFAULT '',
  Socials TEXT NOT NULL DEFAULT '',
  Source TEXT NOT NULL DEFAULT 'Не указано',
  Status TEXT NOT NULL DEFAULT 'New',
  ClientRequest TEXT NOT NULL DEFAULT '',
  Deadline TEXT,
  CreatedAt TEXT NOT NULL,
  OwnerId INTEGER NOT NULL,
  TeamId INTEGER
);
